
import Navbar from "./components/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  console.log(children);
  
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}>
        <div className="flex flex-col min-h-screen">
          <nav>
          <Navbar /> 
          </nav>

          <main className="flex-grow">
            {children}
          </main>

          <footer >
            <div className=" bg-cyan-900 text-white w-full h-60 flex gap-9 ">

            <div className="font-light text-2xl p-9 w-[60%]">BiteBuzz is your go-to partner for unforgettable catering experiences—
              <span className="font-bold text-amber-500">flavorful, fresh, and fuss-free.</span></div>

              <div className="flex flex-col py-9 ">
                <p className="font-bold ">Quick Links</p>
                <Link href='/'   className="hover:text-orange-600">Home</Link>
                <Link href='/Services'  className="hover:text-orange-600">Services</Link>
                <Link href='/About' className="hover:text-orange-600">About</Link>
                <Link href = '/ContactUs' className="hover:text-orange-600">Contact Us</Link>
              </div>
              <div className="flex flex-col py-9 ">
                <p className="font-bold">Contact Info</p>
                <p>📍 Location: Sonepat, Haryana</p>
                <p>📞 Phone: +91-XXXXXXXXXX</p>
                <p>📧 Email: contact@bitebuzz.com</p>
              </div>
              <div className="flex flex-col py-9 ">
                <p className="font-bold">Follow Us</p>
                <p>Instagram</p>
              </div>



            
                
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
